webplatform/Models/Board.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace webplatform.Models
{
    public class Board
    {
        public Guid id { get; set; }

        [Required]
        [DataType(DataType.Text)]
        [Display(Name = "Projektnavn")]
        public string title { get; set; }

        [Required]
        [DataType(DataType.MultilineText)]
        [Display(Name = "Beskrivelse")]
        public string description { get; set; }

        [ForeignKey("Team")]
        public Guid teamId
        {
            get
            {
                return new Guid("23c0cca6-cfd8-11e5-950b-93db59257701");
            }
        }

        //Relations
        public virtual Team team { get; set; }
        public virtual ICollection<Job> jobs { get; set; }
    }
}

webplatform/Controllers/BoardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using webplatform.Models;

namespace webplatform.Controllers
{
    public class BoardController : BaseController
    {
        // GET: Board
        public ActionResult Index(Guid id)
        {   
            return View();
        }
    }
}

webplatform/Controllers/IframeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace webplatform.Controllers
{
    public class IframeController : BaseController
    {
        // GET: Iframe
        public ActionResult Board()
        {
            return View(Context.Boards());
        }

        [HttpPost]
        public ActionResult Board(string search)
        {
            return View(Context.Boards().FindAll(x => x.title.ToLower().Contains(search.ToLower())));
        }

        public ActionResult JobBoard(Guid id)
        {
            return View(Context.FindBoard(id));
        }
    }
}

webplatform/Views/Iframe/Board.cshtml
@model IEnumerable<webplatform.Models.Board>

@{
    Layout = null;
}
<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th style="min-width: 130px;">
                Projekt navn
            </th>
            <th>
                Beskrivelse
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var board in Model)
        {
            <tr class="clickable-row" data-href="@Url.Action("Index", "Board", new {id = board.id})">
                <td>
                    @board.title
                </td>
                <td>
                    <a title="Rediger" href="@Url.Content("~/Form/Board/" + board.id)" data-fancybox-type="iframe" class="editing pull-right"></a>
                    <a title="Extermination of boards" href="@Url.Content("~/api/Database/DeleteBoard/" + board.id)" class="delete pull-right"></a>
                    @board.description
                </td>
            </tr>
        }
    </tbody>
</table>

webplatform/Views/Iframe/Index.cshtml
@model IEnumerable<webplatform.Models.Board>

@{
    Layout = null;
}
<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th style="min-width: 130px;">
                Projekt navn
            </th>
            <th>
                Beskrivelse
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var board in Model)
        {
            <tr class="clickable-row" data-href="@Url.Action("Index", "Board", new {id = board.id})">
                <td>
                    @board.title
                </td>
                <td>
                    <a title="Rediger" href="@Url.Content("~/Form/Board/" + board.id)" data-fancybox-type="iframe" class="editing pull-right"></a>
                    @board.description
                </td>
            </tr>
        }
    </tbody>
</table>

webplatform/Views/Iframe/JobBoard.cshtml
@model webplatform.Models.Board
@{
    Layout = null;
    ViewBag.Title = String.Format("Opgaver for {0}", Model.title);
}

<div class="col-md-12">
    <h2>@ViewBag.Title</h2>
    <a id="new-job" data-fancybox-type="iframe" href="@Url.Content("~/Form/AddJob/")@ViewContext.RouteData.Values["id"]">Opret et job</a> |
    <a id="new-card" data-fancybox-type="iframe" href="@Url.Content("~/Form/AddCard/")@ViewContext.RouteData.Values["id"]">Opret et Card</a>

</div>

<div class="col-md-12" id="content">
    @if (Model.jobs.Count > 0  && !String.IsNullOrEmpty(Model.jobs.First().title))
    {
        foreach (var job in Model.jobs.OrderBy(x => x.weight_id))
        {
            <ul class="list-group pull-left borderless fixed-width" data-id="@job.id">

                <li class="list-group-item item-header main-body">
                    <h3 class="list-group-item-heading">
                        @job.title

                        <a data-fancybox-type="iframe" href="@Url.Content("~/Form/Job/" + @job.id)" class="editing pull-right"></a>
                        <a type="Job" text="@job.title" href="@Url.Content("~/api/Database/DeleteJob/" + job.id)" class="delete pull-right"></a>
                    </h3>
                </li>
                <div class="list-items">
                    @foreach (var card in job.Cards)
                    {
                        <li class="list-group-item feet" style="border-color: @card.color;">
                            <a href="@Url.Content("~/Form/Card/" + card.id)" data-fancybox-type="iframe" class="editing pull-right"></a>
                            <a class="delete pull-right" text="@card.title" type="Card" href="@Url.Content("~/api/Database/DeleteCard/" + card.id)"></a>

                            <h5 class="list-group-item-heading">
                                @card.title
                            </h5>
                            <p class="list-group-item-text">
                                @card.description
                            </p>
                        </li>
                    }
                </div>
            </ul>
        }
    }
</div>